- id: '1601628465190'
  alias: '[general] SpeedTest'
  description: Trigger SpeedTest for your Internet
  trigger:
  - platform: time_pattern
    minutes: /30
  condition: []
  action:
  - service: speedtestdotnet.speedtest
    data: {}
  mode: single
- id: '1601639212345'
  alias: '[general] Car wash notification'
  description: Push notification, that you can wash your car
  trigger:
  - platform: state
    entity_id: binary_sensor.car_wash
    from: 'off'
    to: 'on'
    for: 00:30:00
  condition: []
  action:
  - service: notify.mobile_app_sm_n975f
    data:
      message: Możesz dziś umyć samochód :)
      title: Car wash
  mode: single
- id: '1608056872531'
  alias: '[alarm] Powiadomienie z alarmu'
  description: Powiadomienie o alarmie w domu gdy jesteś daleko
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  condition: []
  action:
  - service: notify.notify
    data:
      title: ALARM!
      message: Alarm w domu!
  - service: persistent_notification.create
    data:
      title: ALARM!
      message: Alarm w domu!
  mode: single
- id: '1608478680935'
  alias: '[alarm] Trigger alarm (AWAY)'
  description: Triggerowanie alarmu z czujników
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d000580336b_contact
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d00062f8d04_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d0005890dbf_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d00070b060e_contact
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d00071172c2_contact
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d00070b0d48_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1608557053776'
  alias: '[climate] Set thermostats, while away'
  description: Ustawia niską temperaturę ogrzewania w sezonie
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: armed_away
  condition:
  - condition: state
    entity_id: input_boolean.sezon_grzewczy
    state: 'on'
  action:
  - service: automation.turn_off
    data: {}
    entity_id: automation.thermostat_schedule
  - service: script.heating_away
    data: {}
  mode: single
- id: '1608557090825'
  alias: '[climate] Set thermostats, while home'
  description: Ustawia wyższą temperaturę ogrzewania w sezonie
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: disarmed
  condition:
  - condition: state
    entity_id: input_boolean.sezon_grzewczy
    state: 'on'
  action:
  - service: automation.turn_on
    data: {}
    entity_id: automation.thermostat_schedule
  mode: single
- id: '1608560967768'
  alias: '[climate] Thermostat schedule'
  description: Skrypt z rozkładem ogrzewania
  trigger:
  - platform: time_pattern
    minutes: /10
    seconds: '00'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: input_boolean.sezon_grzewczy
    state: 'on'
  action:
  - service: python_script.thermostat_scheduler
    data: {}
  mode: single
- id: '1608634414829'
  alias: '[climate] Sezon grzewczy ON'
  description: Włączenie kaloryferów
  trigger:
  - platform: state
    entity_id: input_boolean.sezon_grzewczy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf87b397ec02c5a554ywfj
      hvac_mode: auto
    entity_id: climate.bf87b397ec02c5a554ywfj
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf859bbe3ceddf4c11t0qe
      hvac_mode: auto
    entity_id: climate.bf859bbe3ceddf4c11t0qe
  mode: single
- id: '1608634442526'
  alias: '[climate] Sezon grzewczy OFF'
  description: Wyłączenie kaloryferów
  trigger:
  - platform: state
    entity_id: input_boolean.sezon_grzewczy
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf87b397ec02c5a554ywfj
      hvac_mode: 'off'
    entity_id: climate.bf87b397ec02c5a554ywfj
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf859bbe3ceddf4c11t0qe
      hvac_mode: 'off'
    entity_id: climate.bf859bbe3ceddf4c11t0qe
  mode: single
- id: '1610048949961'
  alias: '[climate] Wyłącz ogrzewanie bo okno'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: 'off'
    to: 'on'
    for: 00:00:30
  condition: []
  action:
  - service: automation.turn_off
    data:
      entity_id: automation.thermostat_schedule
  - service: climate.set_temperature
    data:
      entity_id: climate.bf87b397ec02c5a554ywfj
      hvac_mode: auto
      temperature: 15
    entity_id: climate.bf87b397ec02c5a554ywfj
  mode: single
- id: '1610049167719'
  alias: '[climate] Włącz ogrzewanie bo okno'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: automation.turn_on
    data:
      entity_id: automation.thermostat_schedule
  mode: single
- id: '1610049420662'
  alias: '[alarm] Trigger alarm (NIGHT)'
  description: Triggerowanie alarmu z czujników
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d000580336b_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1610054777017'
  alias: '[alarm] Zamknij drzwi'
  description: Przypomnienie o otwartych drzwiach
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d000580336b_contact
    from: 'off'
    to: 'on'
    for: 00:01:00
  condition: []
  action:
  - service: notify.notify
    data:
      title: DRZWI!
      message: Zamknij za sobą drzwi!
  mode: single
- id: '1610055061956'
  alias: '[climate] Zamknij balkon bo zimno'
  description: Przypomnienie o otwartych drzwiach balkonowych
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    for: 00:05:00
    entity_id: binary_sensor.window
  condition:
  - condition: numeric_state
    entity_id: sensor.ble_temperature_582d34388d0f
    below: '15'
  action:
  - service: notify.mobile_app_sm_n975f
    data:
      message: Balkon
      title: Zamknij balkon!
  mode: single
- id: '1610377241972'
  alias: '[lights] Za ciemno do pracy'
  description: Zielone biurko do pracy
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: device_tracker.plpjarmoszko03_2
    state: home
  action:
  - service: light.turn_on
    data:
      color_name: green
    target:
      device_id: cb86daddd38c338bfb2d5814f42400c1
  - service: light.turn_on
    target:
      device_id: bcf90c079247b3e877a670c465c1815c
  mode: single
- id: '1611317536093'
  alias: '[general] OneMeter notification'
  description: Notification to update OneMeter readout
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.onemeter_timestamp.last_updated)
      > 86400 }}'
  condition:
  - condition: time
    after: 08:00:00
    before: '20:00:00'
  action:
  - service: notify.mobile_app_sm_n975f
    data:
      message: Sprawdź odczyt OneMeter
      title: OneMeter
  - service: notify.persistent_notification
    data:
      title: OneMeter
      message: Sprawdź odczyt OneMeter
  mode: single
- id: '1620640470130'
  alias: '[lights] GAME ON!'
  description: Atmosfera do grania w PS
  trigger:
  - platform: state
    entity_id: device_tracker.playstation_5
    from: not_home
    to: home
  - platform: sun
    event: sunset
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  - condition: device
    device_id: 4b3db5b087017548c34c4ad5d687e9b9
    domain: device_tracker
    entity_id: device_tracker.playstation_5
    type: is_home
  action:
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000ee217a
    data:
      color_name: blue
      brightness_pct: 80
  - service: light.turn_on
    target:
      entity_id: light.sonoff_1000f44d8b
    data:
      color_name: blue
      brightness_pct: 80
  - scene: scene.game_on
  mode: single
- id: '1620834901665'
  alias: '[media] Music - pause'
  description: Pauza muzyki, bo praca w słuchawkach
  trigger:
  - platform: state
    entity_id: sensor.headphones_connection
    from: 'False'
    to: 'True'
  condition:
  - condition: state
    entity_id: media_player.spotify_peetereczek
    state: playing
  - condition: zone
    entity_id: person.piotr
    zone: zone.home
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.samsung_soundbar_q70t_media_playback_status
      state: playing
    - condition: state
      entity_id: switch.skipper_tv
      state: 'on'
  action:
  - service: media_player.media_pause
    target:
      entity_id: media_player.spotify_peetereczek
  mode: single
- id: '1620835229068'
  alias: '[media] Music - play'
  description: Wznów muzykę po zdjęciu słuchawek
  trigger:
  - platform: state
    entity_id: sensor.headphones_connection
    from: 'True'
    to: 'False'
  condition:
  - condition: zone
    entity_id: person.piotr
    zone: zone.home
  - condition: state
    entity_id: sensor.samsung_soundbar_q70t_media_playback_status
    state: paused
  action:
  - service: media_player.media_play
    target:
      entity_id: media_player.spotify_peetereczek
  mode: single
- id: '1620903059726'
  alias: '[lights] Turn all off while sleeping'
  description: Jeżeli telefon uważa, że spisz, wyłącz światła
  trigger:
  - platform: numeric_state
    entity_id: sensor.sm_n975f_pewnosc_snu
    above: '92'
    for: 00:02:00
  condition:
  - condition: zone
    entity_id: person.piotr
    zone: zone.home
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.living_room_rgb
      - light.0x14b457fffef67f86_light
      - light.0xbc33acfffe6f251a
      - light.0xd0cf5efffe32186d
  mode: single
