- id: '1601628465190'
  alias: SpeedTest
  description: Trigger SpeedTest for your Internet
  trigger:
  - platform: time_pattern
    minutes: /30
  condition: []
  action:
  - service: speedtestdotnet.speedtest
    data: {}
  mode: single
- id: '1601639212345'
  alias: Car wash notification
  description: Push notification, that you can wash your car
  trigger:
  - platform: state
    entity_id: binary_sensor.car_wash
    from: 'off'
    to: 'on'
    for: 00:30:00
  condition: []
  action:
  - service: notify.mobile_app_sm_g986b
    data:
      title: Car wash
      message: Możesz dziś umyć samochód :P
  mode: single
- id: '1608056872531'
  alias: Powiadomienie z alarmu
  description: Powiadomienie o alarmie w domu gdy jesteś daleko
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  condition: []
  action:
  - service: notify.notify
    data:
      title: ALARM!
      message: Alarm w domu!
  - service: persistent_notification.create
    data:
      title: ALARM!
      message: Alarm w domu!
  mode: single
- id: '1608478680935'
  alias: Trigger alarm (AWAY)
  description: Triggerowanie alarmu z czujników
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d000580336b_contact
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d00062f8d04_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.0x158d0005890dbf_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1608557053776'
  alias: Set thermostats, while away
  description: Ustawia niską temperaturę ogrzewania w sezonie
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: armed_away
  condition:
  - condition: state
    entity_id: input_boolean.sezon_grzewczy
    state: 'on'
  action:
  - service: automation.turn_off
    data: {}
    entity_id: automation.thermostat_schedule
  - service: script.heating_away
    data: {}
  mode: single
- id: '1608557090825'
  alias: Set thermostats, while home
  description: Ustawia wyższą temperaturę ogrzewania w sezonie
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: disarmed
  condition:
  - condition: state
    entity_id: input_boolean.sezon_grzewczy
    state: 'on'
  action:
  - service: automation.turn_on
    data: {}
    entity_id: automation.thermostat_schedule
  mode: single
- id: '1608560967768'
  alias: Thermostat schedule
  description: Skrypt z rozkładem ogrzewania
  trigger:
  - platform: time_pattern
    minutes: /10
    seconds: '00'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: input_boolean.sezon_grzewczy
    state: 'on'
  action:
  - service: python_script.thermostat_scheduler
    data: {}
  mode: single
- id: '1608634414829'
  alias: Sezon grzewczy ON
  description: Włączenie kaloryferów
  trigger:
  - platform: state
    entity_id: input_boolean.sezon_grzewczy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf87b397ec02c5a554ywfj
      hvac_mode: auto
    entity_id: climate.bf87b397ec02c5a554ywfj
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf859bbe3ceddf4c11t0qe
      hvac_mode: auto
    entity_id: climate.bf859bbe3ceddf4c11t0qe
  mode: single
- id: '1608634442526'
  alias: Sezon grzewczy OFF
  description: Wyłączenie kaloryferów
  trigger:
  - platform: state
    entity_id: input_boolean.sezon_grzewczy
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf87b397ec02c5a554ywfj
      hvac_mode: 'off'
    entity_id: climate.bf87b397ec02c5a554ywfj
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bf859bbe3ceddf4c11t0qe
      hvac_mode: 'off'
    entity_id: climate.bf859bbe3ceddf4c11t0qe
  mode: single
- id: '1610048949961'
  alias: Wyłącz ogrzewanie bo okno
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: 'off'
    to: 'on'
    for: 00:00:30
  condition: []
  action:
  - service: automation.turn_off
    data:
      entity_id: automation.thermostat_schedule
  - service: climate.set_temperature
    data:
      entity_id: climate.bf87b397ec02c5a554ywfj
      hvac_mode: auto
      temperature: 15
    entity_id: climate.bf87b397ec02c5a554ywfj
  mode: single
- id: '1610049167719'
  alias: Włącz ogrzewanie bo okno
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: automation.turn_on
    data:
      entity_id: automation.thermostat_schedule
  mode: single
- id: '1610049420662'
  alias: Trigger alarm (NIGHT)
  description: Triggerowanie alarmu z czujników
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d000580336b_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1610054777017'
  alias: Zamknij drzwi
  description: Przypomnienie o otwartych drzwiach
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d000580336b_contact
    from: 'off'
    to: 'on'
    for: 00:01:00
  condition: []
  action:
  - service: notify.notify
    data:
      title: DRZWI!
      message: Zamknij za sobą drzwi!
  mode: single
- id: '1610055061956'
  alias: Zamknij balkon
  description: Przypomnienie o otwartych drzwiach balkonowych
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    for: 00:05:00
    entity_id: binary_sensor.window
  condition:
  - condition: numeric_state
    entity_id: sensor.ble_temperature_582d34388d0f
    below: '15'
  action:
  - service: notify.mobile_app_sm_g986b
    data:
      title: BALKON!
      message: Nie za dużo tego wietrzenia?
  mode: single
